policies:
  - name: KerasPolicy
    batch_size: 32
    epochs: 1500
    rnn_size: 64
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 38
        state_featurizer:
          - name: BinarySingleStateFeaturizer
  - name: "FallbackPolicy"
    nlu_threshold: 0.01
    core_threshold: 0.01
    fallback_action_name: "utter_default"
