policies:
  - name: "EmbeddingPolicy"
    epochs: 1000
    attn_shift_range: 3
    featurizer:
    - name: FullDialogueTrackerFeaturizer
      state_featurizer:
      - name: LabelTokenizerSingleStateFeaturizer
  - name: "FallbackPolicy"
    nlu_threshold: 0.75
    core_threshold: 0.01
    fallback_action_name: "utter_default"
