language: "en"

pipeline:
- name: "tokenizer_whitespace"
  epoch: 300
- name: "ner_crf"
- name: "ner_spacy"
- name: "nlp_spacy"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
- name: ner_duckling_http
  url: http://localhost:8000
  dimensions:
  - number
